# Generated by Django 4.0.3 on 2022-04-30 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carwash', '0004_remove_order_price_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='resturant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resturant_Item', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='user_Item', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
