# Generated by Django 4.0.3 on 2022-04-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_remove_order_items_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='resturant',
            new_name='user',
        ),
    ]
