# Generated by Django 4.0.3 on 2022-04-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0007_rename_resturant_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='in_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='out_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9999, null=True),
        ),
    ]
