# Generated by Django 4.0.3 on 2022-04-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0008_remove_item_price_item_in_price_item_out_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='both',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
